# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-10 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_mas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_board_date', models.DateField(blank=True, null=True, verbose_name='报到日期')),
                ('name', models.CharField(max_length=120, verbose_name='姓名')),
                ('address', models.CharField(max_length=120, verbose_name='地址')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='直线电话')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='移动电话')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('ver_no', models.IntegerField(default=1, verbose_name='版本号')),
                ('prod', models.CharField(default='User_mas', max_length=20, verbose_name='产品名称')),
                ('func', models.CharField(default='User_mas_add', max_length=20, verbose_name='功能名称')),
                ('maker', models.CharField(default='User_mas', max_length=20, verbose_name='经办员')),
                ('inp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('checker', models.CharField(default='---', max_length=20, verbose_name='复核员')),
                ('app_date', models.DateTimeField(blank=True, verbose_name='修改日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.AlterIndexTogether(
            name='user_mas',
            index_together=set([('status', 'func', 'maker', 'inp_date', 'checker', 'app_date')]),
        ),
    ]
