# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-10 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181110_1017'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user_mas',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='user_mas',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_mas',
        ),
    ]
