# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernal', '0002_auto_20181028_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_mas_tmp',
            name='menu_long_desc',
        ),
        migrations.AddField(
            model_name='menu_mas_tmp',
            name='menu_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='菜单URL'),
        ),
    ]
