# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernal', '0010_auto_20181111_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_mas_log',
            new_name='User_log',
        ),
    ]
