# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-01 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernal', '0011_auto_20181111_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
