# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cif_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易日期')),
                ('id_type', models.CharField(max_length=20, verbose_name='证件类型')),
                ('id_country', models.CharField(max_length=20, verbose_name='证件国别')),
                ('id_no', models.CharField(max_length=120, verbose_name='证件号')),
                ('customer_id', models.CharField(max_length=20, verbose_name='客户号')),
                ('first_name', models.CharField(max_length=120, verbose_name='客户（名）')),
                ('last_name', models.CharField(max_length=120, verbose_name='客户（姓）')),
                ('address', models.CharField(max_length=120, verbose_name='客户地址')),
                ('age', models.IntegerField(verbose_name='客户年龄')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='余额')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='客户电子邮件')),
                ('handphone', models.CharField(blank=True, max_length=20, verbose_name='客户手机')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('ver_no', models.IntegerField(verbose_name='版本号')),
                ('prod', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('func', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('maker', models.CharField(default='Cif_mas', max_length=20, verbose_name='经办员')),
                ('inp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('checker', models.CharField(default='---', max_length=20, verbose_name='复核员')),
                ('app_date', models.DateTimeField(blank=True, verbose_name='修改日期')),
            ],
            options={
                'ordering': ('-tx_date',),
            },
        ),
        migrations.CreateModel(
            name='Cif_mas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20, verbose_name='证件类型')),
                ('id_country', models.CharField(max_length=20, verbose_name='证件国别')),
                ('id_no', models.CharField(max_length=120, verbose_name='证件号')),
                ('customer_id', models.CharField(max_length=20, verbose_name='客户号')),
                ('first_name', models.CharField(max_length=120, verbose_name='客户（名）')),
                ('last_name', models.CharField(max_length=120, verbose_name='客户（姓）')),
                ('address', models.CharField(max_length=120, verbose_name='客户地址')),
                ('age', models.IntegerField(verbose_name='客户年龄')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='余额')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(blank=True, error_messages={'invalid': '格式错了.'}, max_length=254, verbose_name='客户电子邮件')),
                ('handphone', models.CharField(blank=True, max_length=20, verbose_name='客户手机')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('ver_no', models.IntegerField(default=1, verbose_name='版本号')),
                ('prod', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('func', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('maker', models.CharField(default='Cif_mas', max_length=20, verbose_name='经办员')),
                ('inp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('checker', models.CharField(default='---', max_length=20, verbose_name='复核员')),
                ('app_date', models.DateTimeField(blank=True, verbose_name='修改日期')),
            ],
            options={
                'ordering': ('-inp_date',),
            },
        ),
        migrations.CreateModel(
            name='Cif_mas_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20, verbose_name='证件类型')),
                ('id_country', models.CharField(max_length=20, verbose_name='证件国别')),
                ('id_no', models.CharField(max_length=120, verbose_name='证件号')),
                ('customer_id', models.CharField(max_length=20, verbose_name='客户号')),
                ('first_name', models.CharField(max_length=120, verbose_name='客户（名）')),
                ('last_name', models.CharField(max_length=120, verbose_name='客户（姓）')),
                ('address', models.CharField(max_length=120, verbose_name='客户地址')),
                ('age', models.IntegerField(verbose_name='客户年龄')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='余额')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='客户电子邮件')),
                ('handphone', models.CharField(blank=True, max_length=20, verbose_name='客户手机')),
                ('status', models.CharField(blank=True, default='A', max_length=10, verbose_name='状态')),
                ('ver_no', models.IntegerField(default=1, verbose_name='版本号')),
                ('prod', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('func', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('maker', models.CharField(default='Cif_mas', max_length=20, verbose_name='经办员')),
                ('inp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('checker', models.CharField(default='---', max_length=20, verbose_name='复核员')),
                ('app_date', models.DateTimeField(blank=True, verbose_name='修改日期')),
            ],
            options={
                'ordering': ('-inp_date',),
            },
        ),
        migrations.CreateModel(
            name='Cif_tst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=20, verbose_name='证件类型')),
                ('id_country', models.CharField(max_length=20, verbose_name='证件国别')),
                ('id_no', models.CharField(max_length=120, verbose_name='证件号')),
                ('customer_id', models.CharField(max_length=20, verbose_name='客户号')),
                ('first_name', models.CharField(max_length=120, verbose_name='客户（名）')),
                ('last_name', models.CharField(max_length=120, verbose_name='客户（姓）')),
                ('address', models.CharField(max_length=120, verbose_name='客户地址')),
                ('age', models.IntegerField(verbose_name='客户年龄')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='余额')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(blank=True, error_messages={'invalid': '格式错了.'}, max_length=254, verbose_name='客户电子邮件')),
                ('handphone', models.CharField(blank=True, max_length=20, verbose_name='客户手机')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('ver_no', models.IntegerField(default=1, verbose_name='版本号')),
                ('prod', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('func', models.CharField(default='Cif_mas', max_length=20, verbose_name='产品名称')),
                ('maker', models.CharField(default='Cif_mas', max_length=20, verbose_name='经办员')),
                ('inp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('checker', models.CharField(default='---', max_length=20, verbose_name='复核员')),
                ('app_date', models.DateTimeField(blank=True, verbose_name='修改日期')),
            ],
            options={
                'ordering': ('-inp_date',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='cif_tst',
            unique_together=set([('id_type', 'id_country', 'id_no'), ('customer_id',)]),
        ),
        migrations.AlterIndexTogether(
            name='cif_tst',
            index_together=set([('age',), ('func', 'maker', 'inp_date', 'checker', 'app_date'), ('status',), ('first_name', 'last_name')]),
        ),
        migrations.AlterIndexTogether(
            name='cif_mas_tmp',
            index_together=set([('id_type', 'id_country', 'id_no', 'customer_id')]),
        ),
        migrations.AlterIndexTogether(
            name='cif_mas',
            index_together=set([('id_type', 'id_country', 'id_no', 'customer_id')]),
        ),
        migrations.AlterIndexTogether(
            name='cif_log',
            index_together=set([('tx_date', 'customer_id', 'ver_no')]),
        ),
    ]
