# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cif_tst2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('customer_auto_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cif_tst2_id', to='cif.Cif_tst')),
            ],
            options={
                'ordering': ('customer_auto_id2',),
            },
        ),
        migrations.AlterIndexTogether(
            name='cif_tst2',
            index_together=set([('customer_auto_id2', 'column')]),
        ),
    ]
