# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0002_auto_20181003_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cif_tst1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_auto_id', models.CharField(max_length=200)),
                ('column', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('customer_auto_id',),
            },
        ),
        migrations.AlterIndexTogether(
            name='cif_tst1',
            index_together=set([('customer_auto_id', 'column')]),
        ),
    ]
