# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0005_auto_20181003_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cif_tst1',
            options={'ordering': ('cust_id',)},
        ),
        migrations.RenameField(
            model_name='cif_tst1',
            old_name='customer_auto_id',
            new_name='cust_id',
        ),
        migrations.AlterIndexTogether(
            name='cif_tst1',
            index_together=set([('cust_id', 'column')]),
        ),
    ]
