# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cif', '0007_auto_20181003_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cif_tst1',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cif.Cif_tst'),
        ),
    ]
