# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-19 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cif_mas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20)),
                ('id_country', models.CharField(max_length=20)),
                ('id_no', models.CharField(max_length=120)),
                ('customer_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birthday', models.DateTimeField()),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 19, 5, 28, 19, 104328, tzinfo=utc))),
                ('updated', models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 19, 5, 28, 19, 104328, tzinfo=utc))),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 28, 19, 104328, tzinfo=utc)),
        ),
        migrations.AlterIndexTogether(
            name='articlecolumn',
            index_together=set([('id', 'column')]),
        ),
        migrations.AlterIndexTogether(
            name='cif_mas',
            index_together=set([('id_type', 'id_country', 'id_no')]),
        ),
    ]
