# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-19 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180819_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cif_mas',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 7, 3, 18, 927735, tzinfo=utc)),
        ),
    ]
